# Thias file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  # Corne-42 OLED Firmeare
  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DEXTRA_CONF_FILE=../../../../config/corne_oled.conf
    artifact-name: zmk-corne-42-oled-left
  - board: nice_nano_v2
    shield: corne_right
    cmake-args: -DEXTRA_CONF_FILE=../../../../config/corne_oled.conf
    artifact-name: zmk-corne-42-oled-right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-corne-42-oled-settings-reset

  # Corne-42 nice!view Firmeare
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    cmake-args: -DEXTRA_CONF_FILE=../../../../config/corne_niceview.conf
    artifact-name: zmk-corne-42-niceview-left
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    cmake-args: -DEXTRA_CONF_FILE=../../../../config/corne_niceview.conf
    artifact-name: zmk-corne-42-niceview-right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-corne-42-niceview-settings-reset

  # Rolio46.2
  - board: nice_nano_v2
    shield: rolio_left nice_view_adapter vista508
    artifact-name: zmk-rolio-46-left
  - board: nice_nano_v2
    shield: rolio_right nice_view_adapter vista508
    artifact-name: zmk-rolio-46-right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-rolio-46-settings-reset

  # Lili58 Firmeare
  - board: nice_nano_v2
    shield: lily58_left nice_view_adapter nice_view
    artifact-name: zmk-lily58-left
  - board: nice_nano_v2
    shield: lily58_right nice_view_adapter nice_view
    artifact-name: zmk-lily58-right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-lily58-settings-reset
